# Jekyll configuration for GitHub Pages
exclude:
  - node_modules/
  - country-data/node_modules/
  - companies-data/node_modules/
  - event-hunter/node_modules/
  - "*.json"
  - package.json
  - package-lock.json
  - README.md
  - .git/
  - .github/

# Include all HTML files explicitly
include:
  - public.html
  - "*.html"

# GitHub Pages specific settings
plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# Basic Jekyll settings
markdown: kramdown
highlighter: rouge

# Disable Jekyll processing for static HTML files
defaults:
  - scope:
      path: "*.html"
    values:
      layout: null
      sitemap: false 